## APPLICATION CUSTOM CONFIG
app:
  ## Relational Databases
  dataSource:
    master:
      name: master
      driverClass: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.31.148:33006/db_seckill?useSSL=false&autoReconnect=true&useOldAliasMetadataBehavior=true
      username: seckill_app
      password: app@seckill
    slaves:
      slave1:
        name: slave1
        driverClass: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.31.148:33007/db_seckill?useSSL=false&autoReconnect=true&useOldAliasMetadataBehavior=true
        username: seckill_app
        password: app@seckill
      slave2:
        name: slave2
        driverClass: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.31.148:33008/db_seckill?useSSL=false&autoReconnect=true&useOldAliasMetadataBehavior=true
        username: seckill_app
        password: app@seckill
  privateSalt: 29bf9a9a$2dcc$11e7$a638$0090f5f26733
  publicSalt: 29bf9a9a&2dcc&11e7&a638&0090f5f26733
  jwtSecretKey: 3ab6886ccdd23fdd623fc470b53a156b!@#$%^&*
  jwtExpiration: 3600 # 60分钟
  producesPath: /home/net/lovexq/seckill/nginx/data/produce/

## Druid
druid:
  initialSize: 4
  minIdle: 4
  maxActive: 32
  validationQuery: "SELECT 1 FROM DUAL"
  removeAbandoned: true
  removeAbandonedTimeout: 1800
  logAbandoned: 1800

feign:
  compression:
    request:
      enabled : true
      mime-types: text/xml,text/css,text/plain,application/xml,application/json,application/javascript
      min-request-size: 1024
    response:
      enabled : true

## EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  compression:
    enabled: true
    mime-types: text/xml,text/css,text/plain,application/xml,application/json,application/javascript
    min-response-size: 1024
  session-timeout: 3600
  tomcat:
    uri-encoding: UTF-8

## SPRING CONFIGURATION
spring:
  ## devtools
  devtools:
    restart:
      enabled: true
  ## REDIS (RedisProperties)
  redis:
    host: 192.168.31.148
    port: 6379
    database: 0
    pool:
      minIdle: 4
      maxIdle: 32
      maxActive: 64
      maxWait: 60000
    timeout: 10000
  ## RABBITMQ (RabbitMQProperties)
  rabbitmq:
    host: 192.168.31.148
    port: 5672
    username: guest
    password: guest
  ## THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    cache: false # Enable template caching.
    check-template: true # Check that the template exists before rendering it.
    check-template-location: true # Check that the templates location exists.
    content-type: text/html # Content-Type value.
    enabled: true # Enable MVC Thymeleaf view resolution.
    encoding: UTF-8 # Template encoding.
    mode: HTML # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.