server:
  port: 9031-linux
spring:
  application:
    name: microservice-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@127.0.0.1:9001/eureka/
  instance:
    prefer-ip-address: true
  healthcheck:
    enabled: true

# 上传大文件得将超时时间设置长一些，否则会报超时异常。
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 120000