## Druid
druid:
  initialSize: 4
  minIdle: 4
  maxActive: 32
  validationQuery: "SELECT 1 FROM DUAL"
  removeAbandoned: true
  removeAbandonedTimeout: 1800
  logAbandoned: 1800

## LOGGING
logging:
  path: D:/LOGFILE/xq_seckill_microservice
  config: classpath:config/logback.xml
  #OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    application : DEBUG
    druid.sql: DEBUG
    net.lovexq.seckill: DEBUG
    #org.apache.activemq: WARN
    org.apache.http: WARN
    org.hibernate: WARN
    org.springframework: WARN
    org.springframework.boot: DEBUG
    org.springframework.cache: WARN
    org.springframework.data: INFO
    org.thymeleaf: WARN

## EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  compression:
    enabled: true
    mime-types: text/xml,text/css,text/plain,application/xml,application/json,application/javascript
    min-response-size: 1024
  session-timeout: 3600
  tomcat:
    uri-encoding: UTF-8

## SPRING CONFIGURATION
spring:
  ## devtools
  devtools:
    restart:
      enabled: true
  ## REDIS (RedisProperties)
  redis:
    host: 192.168.31.148
    port: 6379
    database: 0
    pool:
      minIdle: 4
      maxIdle: 32
      maxActive: 64
      maxWait: 60000
    timeout: 10000