## Druid
druid:
  initialSize: 4
  minIdle: 4
  maxActive: 32
  validationQuery: "SELECT 1 FROM DUAL"
  removeAbandoned: true
  removeAbandonedTimeout: 1800
  logAbandoned: 1800

feign:
  compression:
    request:
      enabled : true
      mime-types: text/xml,text/css,text/plain,application/xml,application/json,application/javascript
      min-request-size: 1024
    response:
      enabled : true

## EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  compression:
    enabled: true
    mime-types: text/xml,text/css,text/plain,application/xml,application/json,application/javascript
    min-response-size: 1024
  session-timeout: 3600
  tomcat:
    uri-encoding: UTF-8

## SPRING CONFIGURATION
spring:
  ## devtools
  devtools:
    restart:
      enabled: true
  ## REDIS (RedisProperties)
  redis:
    host: 192.168.31.148
    port: 6379
    database: 0
    pool:
      minIdle: 4
      maxIdle: 32
      maxActive: 64
      maxWait: 60000
    timeout: 10000