server:
  port: 10002

spring:
  application:
    name: microservice-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: '${cipher}/a537ad3f8aa1d682cc28244c82e0fbe665f7a2897501956510ede0bc59da2a23736f4c98545f3508c123dc8c6ff23a178dc4d99571952a5e9e8c7ec2b45369aa'
    healthcheck:
      enabled: true

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE