spring:
  application:
    name: microservice-gateway

eureka:
  instance:
    prefer-ip-address: true

# 上传大文件得将超时时间设置长一些，否则会报超时异常。
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 120000