server:
  port: 9031
spring:
  application:
    name: microservice-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@eureka1:9001/eureka/
#      defaultZone: http://eureka1:9001/eureka/,http://eureka2:9002/eureka/,http://eureka3:9003/eureka/
  instance:
    prefer-ip-address: true
  healthcheck:
    enabled: true

# 上传大文件得将超时时间设置长一些，否则会报超时异常。
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 120000