spring:
  application:
    name: microservice-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: '{cipher}6b0607b9f5b757a208b2e9ab30ab84b3223c11e5ad56319f76454382a2d19abf70f7f247d5a05fe7dc7aac340f51b61c3f43951f890484e5624eee722a733b89'
    healthcheck:
      enabled: true

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE