spring:
  application:
    name: microservice-movie
  rabbitmq:
    host: 192.168.31.148
    port: 5673
    username: '{cipher}cbc0a2da8b8c0c7396d9b800a649df2ac7767e47e763ce4cac6729d4797ead26'
    password: '{cipher}cbc0a2da8b8c0c7396d9b800a649df2ac7767e47e763ce4cac6729d4797ead26'

eureka:
  instance:
    prefer-ip-address: true

feign:
  compression:
    request:
      enabled : true
      mime-types: text/xml,text/css,text/plain,application/xml,application/json,application/javascript;
      min-request-size: 1024
    response:
      enabled : true

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG