spring:
  application:
    name: microservice-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: '{cipher}6b0607b9f5b757a208b2e9ab30ab84b3223c11e5ad56319f76454382a2d19abf70f7f247d5a05fe7dc7aac340f51b61c3f43951f890484e5624eee722a733b89'
  instance:
    prefer-ip-address: true
  healthcheck:
    enabled: true

# 上传大文件得将超时时间设置长一些，否则会报超时异常。
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 120000