spring:
  application:
    name: platform-eureka
security:
  basic:
    enabled: true
  user:
    name: platform
    password: p1atf0rmds*lovexq.NET
## LOGGING
logging:
  path: /home/net/lovexq/seckill/log/
  config: classpath:config/logback.xml
  #OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    application: WARN
    com.netflix: WARN
    druid.sql: WARN
    net.lovexq.seckill: WARN
    org.apache.http: WARN
    org.hibernate: WARN
    org.springframework: WARN
    org.springframework.boot: WARN
    org.springframework.cache: WARN
    org.springframework.data: WARN
    org.thymeleaf: WARN

---
spring:
  profiles: node1
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://platform:p1atf0rmds*lovexq.NET@eureka2:8002/eureka
  instance:
    hostname: eureka1

---
spring:
  profiles: node2
server:
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone: http://platform:p1atf0rmds*lovexq.NET@eureka1:8001/eureka
  instance:
    hostname: eureka2