spring:
  application:
    name: platform-eureka
security:
  basic:
    enabled: true
  user:
    name: platform
    password: p1atf0rmds*lovexq.NET
## LOGGING
logging:
  path: /home/net/lovexq/seckill/log/
  config: classpath:config/logback.xml
  #OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    application: INFO
    com.netflix: WARN
    druid.sql: WARN
    net.lovexq.seckill: INFO
    org.apache.http: WARN
    org.hibernate: WARN
    org.springframework: WARN
    org.springframework.boot: WARN
    org.thymeleaf: WARN

## EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  compression:
    enabled: true
    mime-types: text/xml,text/css,text/plain,application/xml,application/json,application/javascript
    min-response-size: 1024
  session-timeout: 3600
  tomcat:
    uri-encoding: UTF-8

---
spring:
  profiles: node1
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://platform:p1atf0rmds*lovexq.NET@eureka2:8002/eureka
  instance:
    hostname: eureka1

---
spring:
  profiles: node2
server:
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone: http://platform:p1atf0rmds*lovexq.NET@eureka1:8001/eureka
  instance:
    hostname: eureka2