spring:
  application:
    name: platform-eureka

security:
  basic:
    enabled: true
  user:
    name: platform
    password: p1atf0rmds*lovexq.NET
---
spring:
  profiles: node1

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://platform:p1atf0rmds*lovexq.NET@eureka2:9002/eureka
  instance:
    hostname: eureka1
---
spring:
  profiles: node2

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://platform:p1atf0rmds*lovexq.NET@eureka1:9001/eureka
  instance:
    hostname: eureka2