server:
  port: 9001

spring:
  application:
    name: platform-eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://platform:p1atf0rmds*lovexq.NET@127.0.0.1:9001/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}@${spring.cloud.client.ipAddress}:${server.port}


security:
  basic:
    enabled: true
  user:
    name: platform
    password: p1atf0rmds*lovexq.NET