server:
  port: 10021

## LOGGING
logging:
  path: /home/net/lovexq/seckill/log/
  config: classpath:config/logback.xml
  #OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    application : INFO
    com.netflix: INFO
    druid.sql: DEBUG
    net.lovexq.seckill: INFO
    org.apache.activemq: WARN
    org.apache.http: WARN
    org.hibernate: WARN
    org.springframework: WARN
    org.springframework.boot: INFO
    org.springframework.cache: WARN
    org.springframework.data: WARN
    org.thymeleaf: WARN