spring:
  application:
    name: platform-zuul
  cloud:
    config:
      profile: dev
      label: master
      username: config
      password: c0nfigds*lovexq.NET
      discovery:
        enabled: true
        service-id: platform-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://platform:p1atf0rmds*lovexq.NET@eureka1:8001/eureka,http://platform:p1atf0rmds*lovexq.NET@eureka2:8002/eureka,
zuul:
  sensitive-headers:
## LOGGING
logging:
  path: /home/net/lovexq/seckill/log/
  config: classpath:config/logback.xml
  #OFF、FATAL、ERROR、WARN、INFO、DEBUG、ALL
  level:
    application: WARN
    com.netflix: WARN
    druid.sql: WARN
    net.lovexq.seckill: WARN
    org.apache.http: WARN
    org.hibernate: WARN
    org.springframework: WARN
    org.springframework.boot: WARN
    org.springframework.cache: WARN
    org.springframework.data: WARN
    org.thymeleaf: WARN